
### Case 1 Create a New Category (Success)
POST http://localhost:8080/api/v1/categories
Content-Type: application/json

{
  "name": "Cosmetics",
  "parentCategoryId": null
}

### Case 2 Create Duplicate (Should return 409 Conflict)
POST http://localhost:8080/api/v1/categories
Content-Type: application/json

{
  "name": "electronics",
  "parentCategoryId": null
}


### Case 3 Get All Categories (Page 1, Sorted by Name)
GET http://localhost:8080/api/v1/categories?page=0&size=5&sort=name,asc
Accept: application/json


### Case 4 Update Category Name (Success) Replace ID with a real one from your DB

PUT http://localhost:8080/api/v1/categories/4c94aef4-244a-4f78-aeb0-8eff5fea9270
Content-Type: application/json

{
  "name": "Electronics",
  "parentCategoryId": null
}

### Case 5 Prevent Self-Parenting (Should return 400 Bad Request)
PUT http://localhost:8080/api/v1/categories/4c94aef4-244a-4f78-aeb0-8eff5fea9270
Content-Type: application/json

{
  "name": "Consumer Electronics",
  "parentCategoryId": "4c94aef4-244a-4f78-aeb0-8eff5fea9270"
}

### Case 6 Delete Category with Sub-categories (Should return 400 Bad Request) Try deleting a parent before deleting its children
DELETE http://localhost:8080/api/v1/categories/4c94aef4-244a-4f78-aeb0-8eff5fea9270

### Case 7 Successful Delete Try deleting a category that has 0 children and 0 products
DELETE http://localhost:8080/api/v1/categories/6452a2a7-2767-459a-9576-60ee4f69d9b2