### LO-S1: Bulk Create Bins (Success)
POST {{baseUrlForLayout}}/storage_bin
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
  "warehouseId": "{{warehouseId}}",
  "zoneId": "{{zoneId}}",
  "aisleId": "{{aisleId}}",
  "quantity": 50,
  "prefix": "B",
  "defaultCapacity": 20
}

### LO-F1: Hierarchy Mismatch Failure (Expected: 400) Logic: Service validates if Aisle belongs to the Zone/Warehouse provided

POST {{baseUrlForLayout}}/aisle
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{ 
    "code": "R-Security", 
    "zoneId": "wrong-zone-id", 
    "warehouseId": "{{warehouseId}}" 
}

### LO-S2: Get Full Warehouse Structure (Admin/Manager)
GET {{baseUrlForLayout}}/warehouse/{{warehouseId}}
Authorization: Bearer {{adminToken}}