package com.infotact.warehouse.entity;

import com.infotact.warehouse.entity.base.WarehouseScopedEntity;
import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.List;

/**
 * Tracks a storage bin rented by a consignment supplier from the warehouse.
 * <p>
 * Revenue = rentalRatePerDay × days for each active rental period.
 * Billing is materialised in {@link BinRentalPayment} records generated by
 * the rental billing scheduler.
 * </p>
 */
@Getter
@Setter
@DynamicInsert
@DynamicUpdate
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(
        name = "bin_rentals",
        indexes = {
                @Index(name = "idx_bin_rental_supplier",  columnList = "supplier_id"),
                @Index(name = "idx_bin_rental_warehouse", columnList = "warehouse_id"),
                @Index(name = "idx_bin_rental_active",    columnList = "active"),
                @Index(name = "idx_bin_rental_dates",     columnList = "start_date, end_date")
        }
)
public class BinRental extends WarehouseScopedEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private String id;

    /**
     * The consignment supplier renting the bin.
     */
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "supplier_id", nullable = false)
    private Supplier supplier;

    /**
     * The specific storage bin being rented.
     */
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "storage_bin_id", nullable = false)
    private StorageBin storageBin;

    /**
     * Agreed rental charge per calendar day in local currency.
     */
    @Column(nullable = false, precision = 19, scale = 4)
    private BigDecimal rentalRatePerDay;

    /**
     * The date from which billing begins (inclusive).
     */
    @Column(nullable = false)
    private LocalDate startDate;

    /**
     * The date on which the rental agreement ends (inclusive).
     * Null indicates an open-ended (month-to-month) rental.
     */
    private LocalDate endDate;

    /**
     * Whether the rental is currently active.
     * Set to false when the supplier vacates the bin or the agreement expires.
     */
    @Column(nullable = false)
    private boolean active = true;

    /**
     * Optional free-text notes (e.g., special terms, bin reservation reason).
     */
    @Column(length = 2000)
    private String notes;

    /**
     * Periodic billing records generated for this rental.
     */
    @OneToMany(mappedBy = "binRental", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    private List<BinRentalPayment> payments;
}
