package com.infotact.warehouse.entity.enums;

/**
 * Payment/settlement lifecycle for a single ConsignmentSettlement record.
 */
public enum ConsignmentSettlementStatus {

    /** Generated by the scheduler; awaiting manager review. */
    PENDING,

    /** Manager approved; payment initiated to supplier. */
    APPROVED,

    /** Payment confirmed as sent to supplier. */
    PAID,

    /** Disputed by the supplier; under investigation. */
    DISPUTED
}
