package com.infotact.warehouse.service.impl;

import com.infotact.warehouse.service.ConsignmentService;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import net.javacrumbs.shedlock.spring.annotation.SchedulerLock;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Component;

import com.infotact.warehouse.entity.ConsignmentAgreement;
import com.infotact.warehouse.entity.ConsignmentSettlement;
import com.infotact.warehouse.repository.ConsignmentAgreementRepository;
import com.infotact.warehouse.repository.WarehouseRepository;

import java.time.LocalDate;
import java.util.List;

/**
 * Scheduled job that automatically generates settlement records when a
 * consignment agreement's cycle period has elapsed.
 *
 * <p>Uses ShedLock to ensure the job runs on only one node in a clustered deployment.
 *
 * <p><b>Schedule:</b> Daily at 01:00 AM (server time).
 * Override via {@code consignment.settlement.cron} in application.properties.
 *
 * <p><b>What it does:</b>
 * <ol>
 *   <li>Queries for ACTIVE agreements whose settlement cycle is due.</li>
 *   <li>For each, delegates to {@link ConsignmentService#generateSettlementInternal}.</li>
 *   <li>Also auto-terminates agreements whose {@code effectiveTo} has passed.</li>
 * </ol>
 */
@Slf4j
@Component
@RequiredArgsConstructor
public class ConsignmentSettlementScheduler {

    private final ConsignmentAgreementRepository agreementRepo;
    private final ConsignmentService consignmentService;
    private final WarehouseRepository            warehouseRepo;

    /**
     * Main settlement job — runs daily at 01:00.
     * ShedLock ensures exactly-once execution across cluster nodes.
     */
    @Scheduled(cron = "${consignment.settlement.cron:0 0 1 * * *}")
    @SchedulerLock(
            name     = "consignmentSettlementJob",
            lockAtLeastFor = "PT5M",
            lockAtMostFor  = "PT30M"
    )
    public void runDailySettlement() {
        log.info("ConsignmentSettlementScheduler: starting daily settlement run");

        LocalDate today = LocalDate.now();

        // Fetch all warehouses and process per tenant
        warehouseRepo.findAll().forEach(warehouse -> {
            try {
                processWarehouse(warehouse.getId(), today);
            } catch (Exception e) {
                log.error("Settlement failed for warehouse {}: {}", warehouse.getId(), e.getMessage(), e);
            }
        });

        log.info("ConsignmentSettlementScheduler: daily settlement run complete");
    }

    private void processWarehouse(String warehouseId, LocalDate today) {
        // 1. Auto-terminate expired agreements
        List<ConsignmentAgreement> expired = agreementRepo.findExpiredAgreements(today);
        for (ConsignmentAgreement agreement : expired) {
            if (!agreement.getWarehouse().getId().equals(warehouseId)) continue;
            log.info("Auto-terminating expired agreement {}", agreement.getAgreementCode());
            try {
                consignmentService.terminateAgreement(
                        agreement.getId(),
                        "Auto-terminated: agreement effective-to date reached on " + today
                );
            } catch (Exception e) {
                log.error("Failed to auto-terminate agreement {}: {}", agreement.getAgreementCode(), e.getMessage());
            }
        }

        // 2. Generate settlements for due agreements
        List<ConsignmentAgreement> due = agreementRepo.findAgreementsDueForSettlement(warehouseId, today);
        log.info("Found {} agreements due for settlement in warehouse {}", due.size(), warehouseId);

        for (ConsignmentAgreement agreement : due) {
            try {
                ConsignmentSettlement settlement =
                        consignmentService.generateSettlementInternal(agreement, "Auto-generated by scheduler");
                if (settlement != null) {
                    log.info("Auto-settlement {} created for agreement {}",
                            settlement.getSettlementNumber(), agreement.getAgreementCode());
                }
            } catch (Exception e) {
                log.error("Failed to generate settlement for agreement {}: {}",
                        agreement.getAgreementCode(), e.getMessage(), e);
            }
        }
    }
}
