package com.infotact.warehouse.service.impl;

import com.infotact.warehouse.entity.ConsignmentAgreement;
import com.infotact.warehouse.entity.ConsignmentSettlement;
import com.infotact.warehouse.repository.ConsignmentAgreementRepository;
import com.infotact.warehouse.service.ConsignmentService;
import com.infotact.warehouse.service.WarehouseService;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import net.javacrumbs.shedlock.spring.annotation.SchedulerLock;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Component;

import java.time.LocalDate;
import java.util.List;

/**
 * Scheduled job that generates settlement records when a consignment
 * agreement's cycle period has elapsed, and auto-terminates expired agreements.
 *
 * <p>Runs daily at 01:00. Uses ShedLock for exactly-once execution.</p>
 */
@Slf4j
@Component
@RequiredArgsConstructor
public class ConsignmentSettlementScheduler {

    private final ConsignmentAgreementRepository agreementRepo;
    private final ConsignmentService             consignmentService;
    private final WarehouseService               warehouseService;

    @Scheduled(cron = "${consignment.settlement.cron:0 0 1 * * *}")
    @SchedulerLock(
            name          = "consignmentSettlementJob",
            lockAtLeastFor = "PT5M",
            lockAtMostFor  = "PT30M"
    )
    public void runDailySettlement() {
        log.info("ConsignmentSettlementScheduler: starting");

        String warehouseId;
        try {
            warehouseId = warehouseService.getSingleWarehouseId();
        } catch (IllegalStateException e) {
            log.info("ConsignmentSettlementScheduler: no warehouse configured yet, skipping.");
            return;
        }

        LocalDate today = LocalDate.now();

        try {
            autoTerminateExpiredAgreements(today);
            generateDueSettlements(warehouseId, today);
        } catch (Exception e) {
            log.error("Settlement run failed: {}", e.getMessage(), e);
        }

        log.info("ConsignmentSettlementScheduler: complete");
    }

    private void autoTerminateExpiredAgreements(LocalDate today) {
        agreementRepo.findExpiredAgreements(today).forEach(agreement -> {
            log.info("Auto-terminating expired agreement {}", agreement.getAgreementCode());
            try {
                consignmentService.terminateAgreement(
                        agreement.getId(),
                        "Auto-terminated: effective-to date reached on " + today
                );
            } catch (Exception e) {
                log.error("Failed to auto-terminate agreement {}: {}",
                        agreement.getAgreementCode(), e.getMessage());
            }
        });
    }

    private void generateDueSettlements(String warehouseId, LocalDate today) {
        List<ConsignmentAgreement> due =
                agreementRepo.findAgreementsDueForSettlement(warehouseId, today);
        log.info("Found {} agreements due for settlement", due.size());

        for (ConsignmentAgreement agreement : due) {
            try {
                ConsignmentSettlement settlement =
                        consignmentService.generateSettlementInternal(
                                agreement, "Auto-generated by scheduler");
                if (settlement != null) {
                    log.info("Auto-settlement {} created for agreement {}",
                            settlement.getSettlementNumber(), agreement.getAgreementCode());
                }
            } catch (Exception e) {
                log.error("Failed to generate settlement for agreement {}: {}",
                        agreement.getAgreementCode(), e.getMessage());
            }
        }
    }
}
